language: php
sudo: required

services:
  - docker

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2
  - 5.6

branches:
  only:
    - feature/new-travis-integration
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DISTRIBUTION=drupal
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

before_install:
  - phpenv config-rm xdebug.ini
  - composer config repositories.drupal '{"type": "composer", "url": "https://packages.drupal.org/8"}'
  - composer require drupal/libraries:~3.0 --no-update
  - composer global require thunder/travis:dev-feature/split-into-stages
  - mkdir libraries
  - wget https://github.com/select2/select2/archive/master.zip
  - unzip  master.zip -d libraries
  - mv libraries/select2-master libraries/select2
  - create-project

install:
  - install-project

script:
  - test-module

notifications:
  email: false
