language: php
dist: xenial

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DRUPAL_TRAVIS_DRUPAL_VERSION=~8.6.0
    - DRUPAL_TRAVIS_DRUPAL_VERSION=~8.7.0
    - DRUPAL_TRAVIS_DRUPAL_VERSION=~8.7.0 DRUPAL_TRAVIS_TEST_DEPRECATION=false
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

matrix:
  allow_failures:
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=~8.7.0


before_install:
  - composer global require thunder/travis

install:
  - test-drupal-project prepare_build
  - composer require npm-asset/select2:4.0.4 --working-dir=/tmp/test/select2/install

script:
  - test-drupal-project

notifications:
  email: false
