language: php
sudo: required

services:
  - docker

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2

branches:
  only:
    - feature/new-travis-integration
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DISTRIBUTION=drupal
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

before_script:
  - composer global require thunder/travis:dev-master

script:
  - test-module


notifications:
  email: false
