language: php
sudo: required

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2
  - 5.6

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DISTRIBUTION=drupal
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - THUNDER_TRAVIS_TEST_GROUP=select3
    - MINK_DRIVER_ARGS_WEBDRIVER='["chrome", null, "http://localhost:4444/wd/hub"]'
    - THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY=/tmp/test-install

before_install:
  - phpenv config-rm xdebug.ini
  - composer global require thunder/travis:fix/drupal-5.6-dev
  - create-project
  - mkdir $THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY/web/libraries
  - wget https://github.com/select2/select2/archive/master.zip
  - unzip  master.zip -d $THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY/web/libraries
  - mv $THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY/web/libraries/select2-master $THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY/web/libraries/select2

install:
  - install-project

script:
  - test-module

notifications:
  email: false
