language: php
sudo: required

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2
  - 5.6

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  matrix:
    - DISTRIBUTION=drupal
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - THUNDER_TRAVIS_SELENIUM_CHROME_VERSION="3.8.1-aluminum"

before_install:
  - phpenv config-rm xdebug.ini
  - composer global require thunder/travis:fix/drupal-5.6-dev
  - create-project

install:
  - install-project

script:
  - test-module

notifications:
  email: false
