<?php

/**
 * @file
 * This is the Select2 module.
 */

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\select2\Plugin\Field\FieldWidget\Select2EntityReferenceWidget;

/**
 * Implements hook_library_info_alter().
 */
function select2_library_info_alter(&$libraries, $extension) {
  if ($extension === 'select2' && function_exists('libraries_get_path')) {
    $libraries['select2.min']['js'] = ['/' . libraries_get_path('select2') . '/dist/js/select2.min.js' => ['minified' => TRUE]];
    $libraries['select2.min']['css']['component'] = ['/' . libraries_get_path('select2') . '/dist/css/select2.min.css' => []];
    foreach (\Drupal::languageManager()->getLanguages() as $language) {
      if (file_exists(libraries_get_path('select2') . '/dist/js/i18n/' . $language->getId() . '.js')) {
        $libraries['select2.i18n.' . $language->getId()] = [
          'js' => [
            '/' . libraries_get_path('select2') . '/dist/js/i18n/' . $language->getId() . '.js' => ['minified' => TRUE],
          ],
          'dependencies' => [
            'select2/select2',
          ],
        ];
      }
    }
  }

  if ($extension === 'seven') {
    $module_path = \Drupal::moduleHandler()->getModule('select2')->getPath();
    $libraries['select2.theme'] = [
      'css' => [
        'component' => [
          "/$module_path/css/select2.seven.css" => [],
          "/$module_path/css/select2.seven-overrides.css" => [],
        ],
      ],
    ];
  }
}

/**
 * Implements hook_library_info_build().
 */
function select2_library_info_build() {
  $libraries = [];
  foreach (\Drupal::languageManager()->getLanguages() as $language) {
    if (file_exists('libraries/select2/dist/js/i18n/' . $language->getId() . '.js')) {
      $libraries['select2.i18n.' . $language->getId()] = [
        'js' => [
          '/libraries/select2/dist/js/i18n/' . $language->getId() . '.js' => ['minified' => TRUE],
        ],
        'dependencies' => [
          'select2/select2',
        ],
      ];
    }
  }
  return $libraries;
}

/**
 * Implements hook_ENTITY_TYPE_presave() for entity_form_display entities.
 *
 * Provides a BC layer for modules providing old configurations.
 *
 * @todo Remove this hook in Drupal 9.0.x
 */
function select2_entity_form_display_presave(EntityFormDisplayInterface $display) {
  /** @var \Drupal\Core\Field\WidgetPluginManager $field_widget_manager */
  $field_widget_manager = \Drupal::service('plugin.manager.field.widget');

  foreach ($display->getComponents() as $field_name => $component) {
    if (empty($component['type'])) {
      continue;
    }

    $plugin_definition = $field_widget_manager->getDefinition($component['type'], FALSE);
    if (!is_a($plugin_definition['class'], Select2EntityReferenceWidget::class, TRUE)) {
      continue;
    }

    if (!isset($component['settings']['match_limit'])) {
      @trigger_error(sprintf('Any select2_entity_reference component of an entity_form_display must have a match_limit setting. The %s field on the %s form display is missing it. This BC layer will be removed before 9.0.0.', $field_name, $display->id()), E_USER_DEPRECATED);
      $component['settings']['match_limit'] = 10;
      $display->setComponent($field_name, $component);
    }
  }
}
