<?php

/**
 * @file
 * This is the Select2 module.
 */

/**
 * Implements hook_library_info_alter().
 */
function select2_library_info_alter(&$libraries, $extension) {
  if ($extension === 'select2' && function_exists('libraries_get_path')) {
    $libraries['select2.min']['js'] = ['/' . libraries_get_path('select2') . '/dist/js/select2.min.js' => ['minified' => TRUE]];
    $libraries['select2.min']['css']['component'] = ['/' . libraries_get_path('select2') . '/dist/css/select2.min.css' => []];
  }
}
