name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        php-version: '7.3'

    - name: Add composer to PATH var
      run: echo "::add-path::$HOME/.composer/vendor/bin"
      
    - name: Get build environment
      run: composer global require thunder/travis

    - name: Install dependencies
      run: test-drupal-project prepare_build

    - name: Get select2 library
      run: composer require npm-asset/select2:^4.0.7 --working-dir=/tmp/test/select2/install --no-update

    - name: Run tests
      run: test-drupal-project
