name: Run module tests

on:
  pull_request:
    branches:
      - 8.x-[1-9]+.x

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        DRUPAL_TRAVIS_DRUPAL_VERSION: ['~8.7.0', '~8.8.0']
        DRUPAL_TRAVIS_TEST_DEPRECATION: ['true', 'false']
        exclude:
          - DRUPAL_TRAVIS_DRUPAL_VERSION: '~8.7.0'
            DRUPAL_TRAVIS_TEST_DEPRECATION: 'false'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        coverage: none
        php-version: '7.3'

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Cache NPM dependencies
      id: npm-cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache
        restore-keys: ${{ runner.os }}-npm-cache

    - name: Setup environment variables
      run: |
        echo "::add-path::$HOME/.composer/vendor/bin"
        echo "::set-env name=DRUPAL_TRAVIS_USE_SELENIUM::true"
        echo '::set-env name=DRUPAL_TRAVIS_DRUPAL_VERSION::${{ matrix.DRUPAL_TRAVIS_DRUPAL_VERSION }}'
        echo '::set-env name=DRUPAL_TRAVIS_TEST_DEPRECATION::${{ matrix.DRUPAL_TRAVIS_TEST_DEPRECATION }}'

    - name: Get build environment
      run: composer global require thunder/travis

    - name: Check PHP coding styles
      run: test-drupal-project coding_style
      env:
        DRUPAL_TRAVIS_TEST_JAVASCRIPT: false

    - name: Check eslint coding styles
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.github_token }}

    - name: Check coding styles and setup the environment
      run: test-drupal-project prepare_build

    - name: Add select2 library to the composer dependencies
      run: composer require npm-asset/select2:^4.0.7 --working-dir=/tmp/test/select2/install --no-update

    - name: Build docroot, test for deprecations, install drupal and run the tests
      run: test-drupal-project
