name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        php-version: '7.3'
        coverage: none

    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '77.0.3865.40'
    - run: |
        export DISPLAY=:99
        chromedriver --port=4444 --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    
    - name: Add composer to PATH var
      run: echo "::add-path::$HOME/.composer/vendor/bin"
      
    - name: Get build environment
      run: composer global require thunder/travis

    - name: Install dependencies
      run: test-drupal-project prepare_build

    - name: Get select2 library
      run: composer require npm-asset/select2:^4.0.7 --working-dir=/tmp/test/select2/install --no-update

    - name: Run tests
      run: test-drupal-project
