name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.3' ]
        include:
          - php: '7.3'
            DRUPAL_TRAVIS_DRUPAL_VERSION: ['~8.7.0']
          - php: '7.3'
            DRUPAL_TRAVIS_TEST_DEPRECATION: ['false']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        coverage: none
        php-version: ${{ matrix.php }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-dir)"

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Setup NPM cache
      id: npm-cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache
        restore-keys: ${{ runner.os }}-npm-cache

    - name: Add composer's bin directory to the PATH environment variable
      run: |
        echo "::add-path::$HOME/.composer/vendor/bin"
        echo "::set-env name=DRUPAL_TRAVIS_USE_SELENIUM::true"
        echo "::set-env name=DRUPAL_TRAVIS_TEST_FILTER::foo"
        echo '::set-env name=DRUPAL_TRAVIS_DRUPAL_VERSION::${{ matrix.DRUPAL_TRAVIS_DRUPAL_VERSION }}'

    - name: Get build environment
      run: composer global require thunder/travis:dev-update-phpstan

    - name: Check coding styles
      run: test-drupal-project prepare_build

    - name: Add select2 library to the composer dependencies
      run: composer require npm-asset/select2:^4.0.7 --working-dir=/tmp/test/select2/install --no-update

    - name: Install drupal and run the tests
      run: test-drupal-project
